import { Job, Application } from "@/lib/types";

// Mock data - will be replaced with API calls
export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Security Analyst",
    department: "Investigations",
    location: "Nairobi, Kenya",
    type: "Full-time",
    salary: "KES 150,000 - 200,000",
    description: "We are looking for an experienced Security Analyst to join our Investigations team. You will be responsible for conducting thorough background checks, due diligence assessments, and risk evaluations for our corporate clients across Africa.",
    requirements: [
      "Bachelor's degree in Criminal Justice, Security Studies, or related field",
      "5+ years experience in security analysis or investigations",
      "Strong analytical and report writing skills",
      "Knowledge of East African regulatory frameworks",
      "Valid security clearance",
    ],
    postedDate: "2026-02-20",
    closingDate: "2026-03-30",
    status: "open",
  },
  {
    id: "2",
    title: "Due Diligence Researcher",
    department: "Due Diligence",
    location: "Nairobi, Kenya",
    type: "Full-time",
    salary: "KES 80,000 - 120,000",
    description: "Join our Due Diligence team to conduct comprehensive commercial due diligence for private equity firms and corporations. You will research companies, individuals, and markets across the African continent.",
    requirements: [
      "Bachelor's degree in Business, Finance, or Law",
      "2+ years experience in research or due diligence",
      "Excellent research and analytical skills",
      "Proficiency in English and Swahili",
      "Attention to detail and ability to work under deadlines",
    ],
    postedDate: "2026-02-25",
    closingDate: "2026-04-05",
    status: "open",
  },
  {
    id: "3",
    title: "Fleet Operations Manager",
    department: "Fleet Management",
    location: "Mombasa, Kenya",
    type: "Full-time",
    salary: "KES 100,000 - 150,000",
    description: "Manage our fleet operations including GPS tracking, vehicle valuation, and asset management services for our growing client base along the coastal region.",
    requirements: [
      "Bachelor's degree in Logistics, Engineering, or related field",
      "3+ years experience in fleet management",
      "Knowledge of GPS tracking systems",
      "Valid driver's license",
      "Strong organizational and leadership skills",
    ],
    postedDate: "2026-03-01",
    closingDate: "2026-04-15",
    status: "open",
  },
  {
    id: "4",
    title: "Hospitality Recruiter",
    department: "Recruitment",
    location: "Nairobi, Kenya",
    type: "Contract",
    salary: "KES 60,000 - 80,000",
    description: "We need a dedicated recruiter to source and screen candidates for our hospitality staffing services. You will work closely with hotels, restaurants, and event companies to fulfill their staffing needs.",
    requirements: [
      "Diploma in HR Management or related field",
      "1+ years experience in recruitment",
      "Knowledge of the hospitality industry",
      "Excellent communication and interpersonal skills",
      "Ability to work flexible hours",
    ],
    postedDate: "2026-03-03",
    closingDate: "2026-03-25",
    status: "open",
  },
  {
    id: "5",
    title: "Debt Collection Officer",
    department: "Debt Recovery",
    location: "Nairobi, Kenya",
    type: "Full-time",
    salary: "KES 70,000 - 100,000",
    description: "Join our debt recovery team to handle commercial debt collection and asset tracing for corporate clients. Strong negotiation skills required.",
    requirements: [
      "Diploma in Business or related field",
      "2+ years experience in debt collection",
      "Knowledge of Kenyan debt recovery laws",
      "Negotiation and conflict resolution skills",
      "Proficiency in MS Office",
    ],
    postedDate: "2026-02-15",
    closingDate: "2026-03-10",
    status: "closed",
  },
];

export const mockApplications: Application[] = [
  {
    id: "a1",
    jobId: "1",
    jobTitle: "Senior Security Analyst",
    applicantName: "James Mwangi",
    email: "james.mwangi@email.com",
    phone: "+254 712 345 678",
    appliedDate: "2026-02-22",
    status: "reviewing" as const,
    coverLetter: "I have 7 years of experience in security analysis...",
  },
  {
    id: "a2",
    jobId: "2",
    jobTitle: "Due Diligence Researcher",
    applicantName: "Amina Hassan",
    email: "amina.h@email.com",
    phone: "+254 723 456 789",
    appliedDate: "2026-02-28",
    status: "shortlisted" as const,
    coverLetter: "With my background in financial research...",
  },
  {
    id: "a3",
    jobId: "1",
    jobTitle: "Senior Security Analyst",
    applicantName: "Peter Ochieng",
    email: "peter.o@email.com",
    phone: "+254 734 567 890",
    appliedDate: "2026-02-25",
    status: "new" as const,
    coverLetter: "I am a certified security professional...",
  },
  {
    id: "a4",
    jobId: "3",
    jobTitle: "Fleet Operations Manager",
    applicantName: "Faith Wanjiku",
    email: "faith.w@email.com",
    phone: "+254 745 678 901",
    appliedDate: "2026-03-02",
    status: "interview" as const,
    coverLetter: "I have managed fleet operations for 5 years...",
  },
  {
    id: "a5",
    jobId: "4",
    jobTitle: "Hospitality Recruiter",
    applicantName: "Daniel Kipchoge",
    email: "dan.k@email.com",
    phone: "+254 756 789 012",
    appliedDate: "2026-03-04",
    status: "new" as const,
    coverLetter: "My experience in the hospitality sector...",
  },
];
